version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=flight-data
      - POSTGRES_PASSWORD=postgres
      - DEBUG=true
    volumes:
      - ./data/db:/var/lib/postgresql/data
